//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceTest.SRVivienda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DVivienda", Namespace="http://schemas.datacontract.org/2004/07/SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class DVivienda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MetrajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServiceTest.SRVivienda.DResidente ResidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Metraje {
            get {
                return this.MetrajeField;
            }
            set {
                if ((this.MetrajeField.Equals(value) != true)) {
                    this.MetrajeField = value;
                    this.RaisePropertyChanged("Metraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumVivienda {
            get {
                return this.NumViviendaField;
            }
            set {
                if ((this.NumViviendaField.Equals(value) != true)) {
                    this.NumViviendaField = value;
                    this.RaisePropertyChanged("NumVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceTest.SRVivienda.DResidente Residente {
            get {
                return this.ResidenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenteField, value) != true)) {
                    this.ResidenteField = value;
                    this.RaisePropertyChanged("Residente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DResidente", Namespace="http://schemas.datacontract.org/2004/07/SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class DResidente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRVivienda.IViviendas")]
    public interface IViviendas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViviendas/CrearVivienda", ReplyAction="http://tempuri.org/IViviendas/CrearViviendaResponse")]
        SOAPServiceTest.SRVivienda.DVivienda CrearVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViviendas/ObtenerVivienda", ReplyAction="http://tempuri.org/IViviendas/ObtenerViviendaResponse")]
        SOAPServiceTest.SRVivienda.DVivienda ObtenerVivienda(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViviendas/ModificarVivienda", ReplyAction="http://tempuri.org/IViviendas/ModificarViviendaResponse")]
        SOAPServiceTest.SRVivienda.DVivienda ModificarVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViviendas/EliminarVivienda", ReplyAction="http://tempuri.org/IViviendas/EliminarViviendaResponse")]
        void EliminarVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViviendas/ListarTodosLasViviendas", ReplyAction="http://tempuri.org/IViviendas/ListarTodosLasViviendasResponse")]
        SOAPServiceTest.SRVivienda.DVivienda[] ListarTodosLasViviendas();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViviendasChannel : SOAPServiceTest.SRVivienda.IViviendas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViviendasClient : System.ServiceModel.ClientBase<SOAPServiceTest.SRVivienda.IViviendas>, SOAPServiceTest.SRVivienda.IViviendas {
        
        public ViviendasClient() {
        }
        
        public ViviendasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViviendasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViviendasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViviendasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServiceTest.SRVivienda.DVivienda CrearVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda) {
            return base.Channel.CrearVivienda(dvivienda);
        }
        
        public SOAPServiceTest.SRVivienda.DVivienda ObtenerVivienda(int codigo) {
            return base.Channel.ObtenerVivienda(codigo);
        }
        
        public SOAPServiceTest.SRVivienda.DVivienda ModificarVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda) {
            return base.Channel.ModificarVivienda(dvivienda);
        }
        
        public void EliminarVivienda(SOAPServiceTest.SRVivienda.DVivienda dvivienda) {
            base.Channel.EliminarVivienda(dvivienda);
        }
        
        public SOAPServiceTest.SRVivienda.DVivienda[] ListarTodosLasViviendas() {
            return base.Channel.ListarTodosLasViviendas();
        }
    }
}
