//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServicios.SRCuota {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRCuota.ICuota")]
    public interface ICuota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/CrearCuota", ReplyAction="http://tempuri.org/ICuota/CrearCuotaResponse")]
        SOAPService.Dominio.DCuota CrearCuota(SOAPService.Dominio.DCuota dcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ObtenerCuota", ReplyAction="http://tempuri.org/ICuota/ObtenerCuotaResponse")]
        SOAPService.Dominio.DCuota ObtenerCuota(int idcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ModificarCuota", ReplyAction="http://tempuri.org/ICuota/ModificarCuotaResponse")]
        SOAPService.Dominio.DCuota ModificarCuota(SOAPService.Dominio.DCuota dcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/EliminarCuota", ReplyAction="http://tempuri.org/ICuota/EliminarCuotaResponse")]
        void EliminarCuota(int idcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ListarCuotas", ReplyAction="http://tempuri.org/ICuota/ListarCuotasResponse")]
        SOAPService.Dominio.DCuota[] ListarCuotas();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuotaChannel : TestServicios.SRCuota.ICuota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuotaClient : System.ServiceModel.ClientBase<TestServicios.SRCuota.ICuota>, TestServicios.SRCuota.ICuota {
        
        public CuotaClient() {
        }
        
        public CuotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPService.Dominio.DCuota CrearCuota(SOAPService.Dominio.DCuota dcuota) {
            return base.Channel.CrearCuota(dcuota);
        }
        
        public SOAPService.Dominio.DCuota ObtenerCuota(int idcuota) {
            return base.Channel.ObtenerCuota(idcuota);
        }
        
        public SOAPService.Dominio.DCuota ModificarCuota(SOAPService.Dominio.DCuota dcuota) {
            return base.Channel.ModificarCuota(dcuota);
        }
        
        public void EliminarCuota(int idcuota) {
            base.Channel.EliminarCuota(idcuota);
        }
        
        public SOAPService.Dominio.DCuota[] ListarCuotas() {
            return base.Channel.ListarCuotas();
        }
    }
}
