//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominios.SRCuota {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCuota", Namespace="http://schemas.datacontract.org/2004/07/SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class DCuota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condominios.SRCuota.DVivienda ViviendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnioField, value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuota {
            get {
                return this.IdCuotaField;
            }
            set {
                if ((this.IdCuotaField.Equals(value) != true)) {
                    this.IdCuotaField = value;
                    this.RaisePropertyChanged("IdCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condominios.SRCuota.DVivienda Vivienda {
            get {
                return this.ViviendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ViviendaField, value) != true)) {
                    this.ViviendaField = value;
                    this.RaisePropertyChanged("Vivienda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DVivienda", Namespace="http://schemas.datacontract.org/2004/07/SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class DVivienda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MetrajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condominios.SRCuota.DResidente ResidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Metraje {
            get {
                return this.MetrajeField;
            }
            set {
                if ((this.MetrajeField.Equals(value) != true)) {
                    this.MetrajeField = value;
                    this.RaisePropertyChanged("Metraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumVivienda {
            get {
                return this.NumViviendaField;
            }
            set {
                if ((this.NumViviendaField.Equals(value) != true)) {
                    this.NumViviendaField = value;
                    this.RaisePropertyChanged("NumVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condominios.SRCuota.DResidente Residente {
            get {
                return this.ResidenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenteField, value) != true)) {
                    this.ResidenteField = value;
                    this.RaisePropertyChanged("Residente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DResidente", Namespace="http://schemas.datacontract.org/2004/07/SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class DResidente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRCuota.ICuota")]
    public interface ICuota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/CrearCuota", ReplyAction="http://tempuri.org/ICuota/CrearCuotaResponse")]
        Condominios.SRCuota.DCuota CrearCuota(Condominios.SRCuota.DCuota dcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ObtenerCuota", ReplyAction="http://tempuri.org/ICuota/ObtenerCuotaResponse")]
        Condominios.SRCuota.DCuota ObtenerCuota(int idcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ModificarCuota", ReplyAction="http://tempuri.org/ICuota/ModificarCuotaResponse")]
        Condominios.SRCuota.DCuota ModificarCuota(Condominios.SRCuota.DCuota dcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/EliminarCuota", ReplyAction="http://tempuri.org/ICuota/EliminarCuotaResponse")]
        void EliminarCuota(int idcuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuota/ListarCuotas", ReplyAction="http://tempuri.org/ICuota/ListarCuotasResponse")]
        Condominios.SRCuota.DCuota[] ListarCuotas();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuotaChannel : Condominios.SRCuota.ICuota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuotaClient : System.ServiceModel.ClientBase<Condominios.SRCuota.ICuota>, Condominios.SRCuota.ICuota {
        
        public CuotaClient() {
        }
        
        public CuotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Condominios.SRCuota.DCuota CrearCuota(Condominios.SRCuota.DCuota dcuota) {
            return base.Channel.CrearCuota(dcuota);
        }
        
        public Condominios.SRCuota.DCuota ObtenerCuota(int idcuota) {
            return base.Channel.ObtenerCuota(idcuota);
        }
        
        public Condominios.SRCuota.DCuota ModificarCuota(Condominios.SRCuota.DCuota dcuota) {
            return base.Channel.ModificarCuota(dcuota);
        }
        
        public void EliminarCuota(int idcuota) {
            base.Channel.EliminarCuota(idcuota);
        }
        
        public Condominios.SRCuota.DCuota[] ListarCuotas() {
            return base.Channel.ListarCuotas();
        }
    }
}
